name: update version code

on:
  workflow_dispatch:
    inputs:
      パラメーター名:
        description: '説明'
        required: true
        default: 'デフォルト値'

jobs:
  update_version_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
      - name: update gradle task
        run:
          ./gradlew incrementVersionCode
          echo ./project.version